# Full overview of ruff rules see at
# https://docs.astral.sh/ruff/rules/#rules
target-version = "py310"
fix = true
cache-dir = ".ruff_cache"
exclude = [
    ".ruff_cache",
    ".venv",
    "venv",
]
indent-width = 4
line-length = 120
output-format = "grouped"


[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[lint]
mccabe.max-complexity = 6
pydocstyle.convention = "google"
select = [
    "ALL",
]
ignore = [
    # "COM812",
    "D100",
    "D104",
    "D107",
]
external = [ "WPS" ]

[lint.extend-per-file-ignores]
"tests/*" = [
    "ANN001",
    "ANN201",
    "ANN202",
    "D101",
    "D102",
    "D103",
    "S101",
    "PLR0913",
    "S113",
    "SLF001",
    "PT011",
    "S105",
    "S603",
    "S607",
    "S106",
] 

[format]
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = 120
indent-style = "space"
quote-style = "single"